name: Deploy to DockerHub

on:
  push:
    branches:
      - deploy
      - bugaton

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/amr .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/amr

      - name: Build and push completed
        run: echo "Deploy to DockerHub completed"
#      - name: Update and restart server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_LOGIN }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          script: |
#            cd ${{ secrets.TARGET_SERVER_PATH }}
#            docker-compose stop
#            docker-compose rm -f frontend
#            docker rmi $(docker images '${{ secrets.DOCKERHUB_USERNAME }}/amr' -q)
#            docker-compose up -d
#
#      - name: Update and restart server completed
#        run: echo "Server updated and restarted"
